name: Create CLI Demo

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [demo]
    paths:
      - 'c4f/**'  # Only when the code changes

jobs:
  create-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          
      - name: Install VHS
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          wget https://github.com/charmbracelet/vhs/releases/download/v0.6.0/vhs_0.6.0_Linux_x86_64.tar.gz
          tar xzf vhs_0.6.0_Linux_x86_64.tar.gz
          sudo mv vhs /usr/local/bin/
          
      - name: Create demo script
        run: |
          cat > demo.tape << 'EOF'
          Output docs/assets/demo.gif
          Set FontSize 18
          Set Width 1200
          Set Height 600
          Set PlaybackSpeed 0.8
          
          # Show help
          Type "c4f --help"
          Sleep 500ms
          Enter
          Sleep 3s
          
          # Show main functionality
          Type "c4f "
          Sleep 500ms
          Type "analyze"
          Sleep 500ms
          Enter
          Sleep 5s
          EOF
          
      - name: Run VHS
        run: vhs demo.tape
        
      - name: Commit and push if demo changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/assets/demo.gif
          git commit -m "Update CLI demo gif" || echo "No changes to commit"
          git push 