name: Create CLI Demo

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [demo]
    paths:
      - 'c4f/**'  # Only when the code changes

# Add these permission settings
permissions:
  contents: write

jobs:
  create-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          
      - name: Install ttyd
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libjson-c-dev libwebsockets-dev
          git clone https://github.com/tsl0922/ttyd.git
          cd ttyd && mkdir build && cd build
          cmake ..
          make && sudo make install
          
      - name: Install VHS
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          wget https://github.com/charmbracelet/vhs/releases/download/v0.6.0/vhs_0.6.0_Linux_x86_64.tar.gz
          tar xzf vhs_0.6.0_Linux_x86_64.tar.gz
          sudo mv vhs /usr/local/bin/
          
      - name: Create demo script
        run: |
          cat > demo.tape << 'EOF'
          Output docs/assets/demo.gif
          Set FontSize 18
          Set Width 1200
          Set Height 600
          Set PlaybackSpeed 0.8
          
          # Show help
          Type "c4f --help"
          Sleep 500ms
          Enter
          Sleep 3s
          
          # Show main functionality
          Type "c4f "
          Sleep 500ms
          Type "analyze"
          Sleep 500ms
          Enter
          Sleep 5s
          EOF
          
      - name: Run VHS
        run: vhs demo.tape
        
      - name: Create ttyd demo script
        run: |
          mkdir -p docs/assets
          cat > docs/assets/launch-demo.sh << 'EOF'
          #!/bin/bash
          ttyd -p 8080 -o -W bash -c "echo 'Welcome to c4f interactive demo!'; echo 'Try running: c4f --help'; bash"
          EOF
          chmod +x docs/assets/launch-demo.sh
          
          cat >> docs/INTERACTIVE_DEMO.md << 'EOF'
          # Interactive Demo
          
          You can try c4f with an interactive terminal demo by running:
          
          ```bash
          # Install ttyd first
          # On macOS: brew install ttyd
          # On Ubuntu/Debian: sudo apt install ttyd
          # Or build from source: https://github.com/tsl0922/ttyd
          
          # Then run the demo script
          ./docs/assets/launch-demo.sh
          ```
          
          Then open your browser to http://localhost:8080
          EOF
        
      - name: Commit and push if demo changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update CLI demo assets"
          file_pattern: "docs/assets/demo.gif docs/assets/launch-demo.sh docs/INTERACTIVE_DEMO.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 