name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --with dev
        
    - name: Run tests
      id: run-tests
      run: |
        python -m pytest -m "not long" --rootdir=. -v --junitxml=test-results.xml
      continue-on-error: true
        
    - name: Check types with mypy
      id: type-check
      run: |
        mypy c4f tests --show-error-codes
      continue-on-error: true
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: test-results.xml
        
    - name: Check job status
      if: steps.run-tests.outcome == 'failure' || steps.type-check.outcome == 'failure'
      run: exit 1